packages:
  - app
  - ui-kit
  - packages/*

catalog:
  '@sveltejs/kit': ^2.55.0
  '@sveltejs/vite-plugin-svelte': ^6.2.4
  svelte: ^5.54.1
  svelte-check: ^4.4.5
  typescript: ^5.9.3
  vite: ^7.3.1

linkWorkspacePackages: true

onlyBuiltDependencies:
  - esbuild

preferWorkspacePackages: true
